[colors]
[colors.primary]
background = '#232136'
foreground = '#e0def4'

# Normal colors
[colors.normal]
black = '#393552'
red = '#eb6f92'
green = '#3e8fb0'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

# Bright colors
[colors.bright]
black = '#6e6a86'
red = '#eb6f92'
green = '#3e8fb0'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ea9a97'
white = '#e0def4'

[colors.selection]
background = '#393552'
